#!/usr/bin/env python3
"""
ABIDES Configuration Generator v1.0.0 - CLI Usage Examples

This file demonstrates various CLI usage patterns for the 
ABIDES Configuration Generator. All examples can be run directly.

Generated by: ABIDES Configuration Generator v1.0.0
"""

import subprocess
import sys
import os

def run_command(description, command):
    """Run a CLI command and show the result"""
    print(f"\n{'='*60}")
    print(f"Example: {description}")
    print(f"Command: {command}")
    print(f"{'='*60}")
    
    result = subprocess.run(command, shell=True, capture_output=True, text=True)
    
    if result.returncode == 0:
        print("✅ Success!")
        if result.stdout:
            print(result.stdout[:500] + "..." if len(result.stdout) > 500 else result.stdout)
    else:
        print("❌ Error!")
        print(result.stderr)

def main():
    """Run example CLI commands"""
    print("ABIDES Configuration Generator v2.0.0 - CLI Examples")
    
    # Check if configgen.py exists
    if not os.path.exists("../configgen.py"):
        print("❌ Error: configgen.py not found in parent directory")
        sys.exit(1)
    
    # Basic examples
    examples = [
        ("List all research templates", 
         "python ../configgen.py --list-templates"),
        
        ("Generate RMSC03 template configuration",
         "python ../configgen.py --template rmsc03 -f rmsc03_example --symbol AAPL"),
        
        ("Generate multi-agent simulation with all 6 agent types",
         "python ../configgen.py -f comprehensive_example --mm 5 --am 3 --mo 8 --zi 150 --no 30 --va 15"),
        
        ("Generate ABIDES-Gym compatible configuration", 
         "python ../configgen.py --template minimal --gym-mode -f gym_example --mm 3 --zi 50"),
        
        ("Generate HFT template with momentum agents",
         "python ../configgen.py --template hft -f hft_momentum --mo 12 --mm 5 --zi 100"),
        
        ("Generate behavioral finance simulation",
         "python ../configgen.py --template behavioral -f behavioral_example --va 20 --no 50 --zi 150"),
        
        ("Show version information",
         "python ../configgen.py --version"),
         
        ("Show help for all options",
         "python ../configgen.py --help")
    ]
    
    # Run examples
    for description, command in examples:
        run_command(description, command)
    
    print(f"\n{'='*60}")
    print("All CLI examples completed!")
    print("Generated configuration files can be found in the current directory.")
    print("Copy them to your ABIDES installation and run with: python config_file.py")
    print(f"{'='*60}")

if __name__ == "__main__":
    main()